name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Build
        run: |
          set -ex
          git clone --depth=1 https://github.com/${GITHUB_REPOSITORY}
          cd $(basename ${GITHUB_REPOSITORY})
          go vet
          go test -v -cover
          go build -v -race
          (cd cmd/fastdig && go build -v)
          (cd cmd/fastdns && go get -v github.com/valyala/fasthttp && go build -v)
