name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          set -ex
          git clone --depth=1 https://github.com/${GITHUB_REPOSITORY}
          cd $(basename ${GITHUB_REPOSITORY})
          go vet
          go build -v -race
          go build -v main.go
          go test -v -cover
